#!/bin/bash
# ESP32tRNS Release: build firmware + convert to UF2
# Usage:
#   ./release.sh           — build + git tag + push
#   ./release.sh --no-tag  — только сборка, без коммита
set -e
export PATH="$HOME/bin:/usr/local/bin:/usr/bin:/bin:$PATH"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VERSION=$(cat "$SCRIPT_DIR/VERSION" | tr -d '[:space:]')

# Формат версии: D.D.D.D или D.D.D.D-suffix
[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+(-[a-z]+[0-9]*)?$ ]] \
  || { echo "Bad version: $VERSION"; exit 1; }

echo "=== Build v${VERSION} ==="

# ── version.h ─────────────────────────────────────────────────────────────────
cat > "$SCRIPT_DIR/ESP32tRNS/version.h" << EOF
// Auto-generated by release.sh — не редактировать вручную
#ifndef VERSION_H
#define VERSION_H
#define FIRMWARE_VERSION "$VERSION"
#endif
EOF

# ── Сборка ────────────────────────────────────────────────────────────────────
if ! command -v arduino-cli &>/dev/null; then
  echo "arduino-cli not found, skipping build"
  exit 1
fi

mkdir -p "$SCRIPT_DIR/build"

# ESP32-S3FH4R2 — Lolin S3 Mini (тот же чип, та же разметка флеша)
# USBMode=default  → TinyUSB доступен (нужен для MSC).
# CDCOnBoot=default → USB НЕ поднимается автоматом в initArduino();
#   делаем USB.begin() руками в setup() после задержки —
#   это даёт OTG-контроллеру время "отойти" после TinyUF2.
FQBN="esp32:esp32:lolin_s3_mini:USBMode=default,CDCOnBoot=default"

# Размер ota_0 из partitions.csv: 0x2c0000 = 2883584 байт
OTA0_SIZE=2883584

echo "FQBN: $FQBN"
echo "Compiling..."
arduino-cli compile \
  --fqbn "$FQBN" \
  --build-property "upload.maximum_size=${OTA0_SIZE}" \
  --output-dir "$SCRIPT_DIR/build" \
  "$SCRIPT_DIR/ESP32tRNS"

mv "$SCRIPT_DIR/build/ESP32tRNS.ino.bin" "$SCRIPT_DIR/build/firmware-${VERSION}.bin"

# ── Конвертация в UF2 ─────────────────────────────────────────────────────────
# ESP32-S3 family ID: 0xc47e5767
# ESP32-S2 family ID: 0xbfdd4eee  (для истории)
echo "Converting to UF2..."
python3 "$SCRIPT_DIR/tinyuf2/uf2conv.py" \
  -f 0xc47e5767 \
  -b 0x0 \
  -c "$SCRIPT_DIR/build/firmware-${VERSION}.bin" \
  -o "$SCRIPT_DIR/build/firmware-${VERSION}.uf2"

# Копии без версии — удобно для быстрого дропа на диск
cp "$SCRIPT_DIR/build/firmware-${VERSION}.bin" "$SCRIPT_DIR/build/firmware.bin"
cp "$SCRIPT_DIR/build/firmware-${VERSION}.uf2" "$SCRIPT_DIR/build/firmware.uf2"

echo ""
echo "✓  build/firmware-${VERSION}.bin"
echo "✓  build/firmware-${VERSION}.uf2  ← drop to WS3ZEROBOOT (or LOLIN3MBOOT)"
echo ""

# ── Git tag ───────────────────────────────────────────────────────────────────
if [[ "$1" == "--no-tag" ]] || ! git -C "$SCRIPT_DIR" rev-parse --is-inside-work-tree &>/dev/null; then
  exit 0
fi

TAG="v${VERSION}"
git -C "$SCRIPT_DIR" tag -l | grep -q "^${TAG}$" \
  && { echo "Tag $TAG already exists locally!"; exit 1; }
git -C "$SCRIPT_DIR" ls-remote --tags origin 2>/dev/null | grep -q "refs/tags/${TAG}$" \
  && { echo "Tag $TAG already exists on remote!"; exit 1; }

git -C "$SCRIPT_DIR" add -A
git -C "$SCRIPT_DIR" diff --cached --quiet \
  && { echo "Nothing to commit, skipping tag."; exit 0; }

git -C "$SCRIPT_DIR" commit -m "chore: v${VERSION}"
git -C "$SCRIPT_DIR" tag -a "$TAG" -m "Release ${VERSION}"
git -C "$SCRIPT_DIR" push origin "$TAG"
echo "Tagged: $TAG"
